#-------------------------------
# General Site Settings
title: Olympia
logo: logo2.png # You can add own logo.
description: Workspace and project highlights


#-------------------------------
# Author Settings
author: 
  name: Andrew Seo
  image: bottle5.png
  say-hello: Introducing, <strong>the Olympia Bottle</strong>
  bio: Hydration tracking seen like <strong>never before.</strong>

#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle

